@extends('layouts.app')
@section('title','Terms and Conditions')
@section('links')
@include('includes.links')
<style>
    ol {
       margin-left: 22px;
       margin-bottom: 20px;
    }
    ol li {
       color: rgb(63 63 63);
       list-style: unset;
       margin-bottom: 11px;
    }
</style>
@endsection
@section('headers')
@include('includes.header')
@endsection
@section('content')

<section class="pager-section banner_img">
    <div class="container">
        <div class="main-banner-content p-relative">
            <div class="social-links">
                <ul>
                    <li><a href="#" title=""><i class="fab fa-linkedin"></i></a></li>
                    <li><a href="#" title=""><i class="fab fa-twitter"></i></a></li>
                    <li><a href="#" title=""><i class="fab fa-facebook-f"></i></a></li>
                </ul>
            </div><!--social-links end-->
            <div class="pager-content">
                <ul class="breadcrumb-list">
                    <li><a href="{{route('home')}}" title="">Home</a></li>
                    <li><span>Terms Of Services</span></li>
                </ul><!--breadcrumb end-->
                <h2 class="page-title">Terms Of Services</h2>
            </div><!--pager-content end-->
        </div><!--main-banner-content end-->
    </div>
</section><!--pager-section end-->

<div class="gig-details-pg-inr prvc-pg-inr">
    <div class="container">
       <div class="prvt-hd">
          <h2>Terms Of Services</h2>
       </div>
       <div class="gig-sec-1">

          <div class="prvt-txt-bg">
             <p>Bequest Records Pvt Ltd (“Bequest” "we", "us" and “our”), a Company duly incorporated and registered under the Companies Act, 2013 along with its brand “Will & More” extends a warm welcome to the users of its website <a href="https://www.willandmore.com/"  style="color:#f43930;">www.willandmore.com</a> (“our website”) as well as the general public who may access the website for information and awareness. </p>
             <p>This document provides the Terms and Conditions for accessing and/or using our website by Members/Clients and/or the general public (“User”, “Customer”, “Client”, “Member”, “you”) and for availing the facilities/ services/ products offered by us. </p>
             <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and user agreement for access or usages of websites. </p>
             <p>Please read these Terms of Use, carefully. By accessing and using the Website, you agree to be bound by these Terms of Use. You may use this website if and only if you agree with the conditions mentioned here in totality; therefore, use of our website will signify your acceptance of all Terms & Conditions mentioned here in entirety, without any variation whatsoever. </p>
             <p>These Terms and conditions and the disclaimers herein shall be applicable to any person visiting/accessing our website and/or a user entering into an agreement related to availing of the facilities/services offered by us. When using the Website, you will be subject to these and any additionally posted guidelines or rules applicable to specific media, services, and features, which may be posted from time to time (“the Guidelines”). All such Guidelines are hereby incorporated by references into this Terms of Use. </p>
             <p>Before accessing our web site, you are required to first read and understand these Terms and Conditions, the Privacy Policy and the Disclaimer Policy as published in the relevant pages / portions of our website and convey/ transmit to us such understanding and your acceptance of these Terms and Conditions, the Privacy Policy and the Disclaimer Policy by electronically ticking the relevant box and transmitting the acceptance to us electronically. Only after such transmission to us will you be able to access our website and the contents thereof. </p>
             <p>Please note that by accessing this website, you acknowledge that you have read, understood and agree to be bound by the terms and conditions mentioned below. Before using the website for any purpose, you agree to understand the services and information provided by/through the website, and shall not plead ignorance or lack of understanding of any service or facility in any matter and hold it against Bequest/us. </p>
          </div>

          <div class="prvt-txt-bg">
           <h5>PART 1 – GENERAL TERMS OF USE</h5>
          </div>
          <div class="prvt-txt-bg">
               <h4>You acknowledge, agree and confirm that: -</h4>
               <ol type="1">

                   <li>You have all attributes as required under applicable Laws of India for you to Enter into a valid and legally binding contract, including but not limited to your attainment of the age of 18 years, being of a sound mind and not suffering from any legal limitations/debarment or you have received parental consent and are under parental supervision when using our website; </li>

                   <li>All the information you provide is truthful, current, complete and accurate and that you have not concealed anything material in any respect; that your use of our website does not violate any applicable law or regulation; You provide incorrect or incomplete information at your own risk and responsibility and that you alone shall be liable and responsible for all legal (civil and criminal) consequences. We reserve the right to suspend/deactivate your account & any current or future transactions in case you provide any incorrect information or fail to comply with any statutory requirement, whether current or future. </li>

                   <li>We reserve the right to provide and disclose any information as desired by any statutory, law enforcing or regulatory authority, including the information about the transactions effected by you through this website in regular course or otherwise and such an act by us shall not cause the derogation of our rights with respect to these terms nor shall it cause other terms to be null and void or be considered a violation of any terms and conditions contained herein. </li>

                   <li>Disclosure of information, made in accordance with the requirements of law, by us will not amount to breach of trust or a breach of privacy. For an explanation of our practices and policies related to the collection, use, and storage of our Users' information, please read our <a href="{{route('privacy_policy')}}" style="color:#f43930;">Privacy Policy.</a> </li>

                   <li>The access and or use by you of our website shall be deemed to be unauthorised if the terms and conditions contained herein, in part or in full including this paragraph are not recognized and or not capable of being enforced in the country and or jurisdiction from where you have voluntarily or otherwise accessed and/or used our web site in any manner. </li>

                   <li>We provide you  facilities to register the location of your Will, to record a Letter of Instructions to your loved ones, to cause a search if the location of your Will and Letter of Instructions has been registered with us; we have also made available for download, templates of Wills along with detailed instructions on how to make a Will. Additionally, we have provided Clients a facility to automatically generate a Will document as per your requirement with all the details and the distribution of your assets as you may stipulate in a format that shall be decided and filled up by you and with added features to edit the draft on-line document and finally generate a printed version for you to execute and get it witnessed. The objective of this website is to provide you the convenience of viewing online the details of facilities and the services offered by us and other general information about Wills and the law and practice relating to Wills and to help you take a considered decision at the convenience and comfort of your own home or work spot.  We also extend off site consultation service regarding drafting of Wills and also assist in drafting “Customised” Will documents as per certain unique or specific requirements that you may have. </li>

                   <li>The assistance, documents and information provided to you through our website does not constitute Legal Advice or Legal Opinion or Financial or Tax Advice; the same is only based on general information about prevailing laws and regulations relating to personal succession, Wills and Estate planning in India or assets based in India and on various issue relating to personal laws in India and also news, latest updates, judgments, cases and other allied information pertaining thereto to the best of our knowledge and information available in the public domain. </li>

                   <li>Apart from the Off-line and oral consultation that we may offer clients upon their specific request, we offer all our other facilities and services through electronic means and in electronic mode and we reserve the right to accept Members/Users/clients as we may deem fit. However, we make no guarantee or representation as to, and shall have no liability for, any electronic content delivered by any third party, including the accuracy, subject matter, quality or timeliness of any electronic content on our website. </li>

                   <li>The facilities and services are provided on an “as is” basis. Bequest and its affiliates/ Directors/ Promoters disclaim any warranty of any kind, imputed by the laws of any jurisdiction, whether express or implied, as to any matter whatsoever relating to the service, including without limitation the implied warranties of merchantability, fitness for a particular purpose and non – infringement. Bequest is not responsible for the content of any of the linked sites. By providing access to other websites, Bequest is neither recommending nor endorsing the content available in the linked websites. Bequest also does not take any responsibility for the contents published under its “Expert Speak” section or the “Blogs” section as they are contributed/ written by individuals in their own capacity. </li>

                   <li>The services on our website do not constitute an offer to sell or intended for solicitation of any person in any jurisdiction where it is unlawful to make such an offer or solicitation. The services rendered are not intended to be any form of an advertisement, or opinion or asset distribution or a legal settlement forum relating to the Users/Members/clients assets and is only for the personal use of Member/User/client. </li>

                   <li>You warrant that you shall not use the Information from any part of our website for any illegal or unauthorised purpose. Further, you are aware that it is forbidden to link any of the Pages/content as contained in our website  to your own or another website in any way without our express consent in writing.  We hereby put you on notice that in doing so, you will be breaching our and our Web licensors/ developers’ intellectual property rights in the Information/ IT deployed and we reserve the right to take action against you to uphold our rights, which may involve pursuing injunctive proceedings. </li>

                   <li>The content of the website should not be copied, reproduced, republished, uploaded, posted, transmitted or distributed for any non – personal use without obtaining prior written permission from us. </li>

                   <li>The services offered by us through our website may vary from time to time and are at our sole discretion; we reserve the right to amend/withdraw or add any facilities/service at our discretion. We may at times need to edit, alter and or remove any information or transaction mechanism, in whole or in part, which may be available on or accessed through our web site; We will not be responsible for all or any consequences or loss or damage and or liability arising therefrom. </li>

                   <li>The security and developmental concerns necessitate, allow and empower us to alter and/or amend the rights, including access rights and obligations contained herein without any specific notice and/or advice to you and that we may, at our sole and absolute discretion and at any time, terminate your privilege to use our website. </li>

                   <li>We do not make any representation or warranty regarding the standing or credit of any person, firm or company mentioned in the information contained in our website, nor do we guarantee the suitability of the information including the Will templates as contained in our website for any or all purposes. </li>

                   <li>We exercise due care to ensure provisioning of a secure environment and smooth functioning; however due to the volatility & vulnerability of internet, we provide no warranty that the contents of the website and its components are free from viruses or other damaging elements, which have contaminating or destructive properties and therefore, does not accept any liability in respect thereof. In this regard, it may be noted that:
                       <ol type="a">
                           <li>we employ the services of McAfee Corporation to continuously review the website and its facilities for any vulnerabilities and possible attempts to hack into the web-site, </li>

                           <li>an accredited and licensed technology company has carried out a Vulnerability Assessment and Penetration Test (“VAPT”); i.e.; an exercise by which the IT systems such as computers and networks, and software such as operating systems and application software are scanned in order to identify the presence of known and unknown vulnerabilities. </li>

                           <li>We use cloud servers provided by Amazon Web Services Inc. (“AWS”): to host our website and to store data and records including Will location details, Letter of Instructions and details of Nominees at our sole discretion. </li>

                           <li>Accordingly, there are no IT equipment or systems on the ground that can fail or be attacked locally. </li>
                       </ol>
                   </li>

                   <li>We endeavour to provide but do not guarantee a continuous, uninterrupted or secure access to our website or to any other linked websites. Our website may be unavailable for such period of time as required for technical and/or maintenance reasons or otherwise including during modification and neither we nor our Directors/affiliates shall be liable in any manner whatsoever for such interruption/unavailability of the website/service facilities. </li>

                   <li>We shall not be liable for any consequences arising from the use of any information or software that a Member/User downloads from our website. Further, we are not be liable for consequences arising from a User/Member/customer making a copy, modifying, uploading, downloading, transmitting, (re)publishing it or removing or obscuring any intellectual property, including trademark, copy right or other notices or logos/legends contained in any such information or otherwise distributing any service or content from our website. We shall not bear any responsibility if a User/ Member/customer modifies or uses the content or services he/she obtains from our website for any purpose other than those permitted and in doing so violates the intellectual property rights including trademarks, copyrights and other proprietary rights of any person. The trademarks, logos and service marks available on our web site are invaluable assets of Bequest and/or its agents, associates, subsidiaries and other parties, who have been authorized by Bequest to display the same on our web site. In our endeavour to serve and protect your interests and rights, we will appreciate if you could inform us in writing at support@willandmore.com furnishing all necessary details of the purported violation or infringement of our trademarks, logos and service marks which are either protected by us and or available on our web site. The information thus provided by you would be forwarded to our legal advisors for opinion on all or any legal recourse that can or should be adopted by us in order to protect our intellectual Property rights. </li>

                   <li>We, our Directors, Promoters, shareholders, employees, associates or other representatives and its Affiliates shall not be liable for damages or injury arising out of or in connection with the use of our website or its non-use including non-availability, compensatory, direct, indirect or consequential damages, loss of data, loss or damage to assets/ property (including loss or corruption of data) whether resulting in whole or in part, from/or relating to any of the services offered or displayed on our website. </li>

                   <li>You understand and agree that no joint venture, partnership, employment, or agency relationship exists between us as a result of this association or on account of you accessing and/or using of our website. </li>

                   <li>Save as otherwise provided herein, to the maximum extent permissible by law, all warranties, conditions or terms other than those expressly set out are excluded, including but not limited to implied and statutory conditions and warranties. </li>

                   <li>Our company has been incorporated under the laws of India; you will appreciate that we can only abide and follow the laws of India for entering and/or fulfilling the terms & conditions set out herein. For the sake of jurisdiction, all or any disputes arising out of/or relating to the use of this website, the courts in the city of Mumbai in the state of Maharashtra, India alone shall have jurisdiction. </li>

                   <li>During the existence and subsistence of these terms, if any part hereof is concluded to be invalid or unenforceable in terms of any applicable Indian law, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the other terms shall continue in effect. </li>

                   <li>We reserve the right to change the terms of service or policies regarding the use of our website and/or the products/facilities/ services offered by us at any time and to post an updated version of the facilities and services provided by us on our website, which shall be construed as sufficient notice to you in this regard. It is in your own interest that you review this document periodically for any updates and ensure your familiarity with the most current version. Unless otherwise provided in such revision: -

                       <ol type="a">
                           <li>the revised User Agreement, or its part thereof, will take effect as and when it is posted, that is to say, the last revised date and unless explicitly stated otherwise, </li>

                           <li>any new features that augment or enhance our website shall be subject to these Terms of Use. </li>

                           <li>these “Terms & Conditions” herein supersede the previous terms & conditions, if any, on the matters specified herein. </li>
                       </ol>

                       Any continued use of our website after any such changes shall constitute your consent to such changes. </li>
                   </li>

                   <li>You acknowledge and agree that a printed version of this Agreement and/or any electronic communication with Bequest shall be admissible in judicial or administrative proceedings based upon or relating to this Agreement and/or your use of our website to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. </li>

                   <div class="prvt-txt-bg">
                       <h5>PART 2 – Terms of use for Members</h5>
                   </div>

                   <li>We require all customers who wish to (1) register the location of their Will or (2) store a Letter of Instructions or (3) download a Will format or (4) use the on-line drafting of a Will using a pre-prepared template and filling up or updating all your information related to the generation of a Will document which will be based on the data that you may place in the relevant places of the structured data base and/or avail of other products, services  features and facilities (excluding the off-line consultation with the independent panel of legal experts that we may constitute for drafting a Customised Will as per your specific requirements), offered by us through our website, to sign up for a customer account by completing all required fields on the Registration page on our website and making payment. </li>

                   <li>As a part of the registration process, you agree that you are above 18 years of age and legally competent, that you are entering into a legally binding contract with Bequest with respect to your use of our website and that you have read all policies of this website. You also agree to provide: (a) information about yourself that is truthful, current, complete and accurate; and (b) update this information so as to maintain its accuracy. </li>

                   <li>In order to avail of one or more products, services, features and facilities offered by us, you are required to click on the button “BUY NOW” against each product descriptionor the buttons on “PRICING” part or you may press the  on the “REGISTER NOW” button in the Home Page or other sections of the web site  or in the LOGIN Page in which caseyou will be directed to the “Products/Packages” page where you will be provided with the option to choose from among the various packages products offered.
                       : -
                       Currently, four (4) products/ facilities are offered  by Will & More:
                       <ol type="a">
                           <li><p><b>On-line Will drafting facility:</b> Through this new feature, perhaps for the first time in India, you can get your Will drafted on-line by placing all your relevant details in the database that will be provided to you. The details will include the details of all your assets, both moveable as well as immoveable, those of your investments like the Provident Fund, pension, life insurance, bank deposits, securities (shares, debentures and bonds) as well as your liabilities that you would want to be settled out of your assets etc. There is provision for you to state the name and identity details of your Executor as well as the two witnesses. </p>
                               <p>The data that you place is highly secure and confidential and will be accessible only through your confidential password. The Will once generated can be edited by making appropriate changes I the details placed by you in the data base assigned to you. </p>
                               <p>The Will document that you generate will be in a PDF version which you can print and then subscribe your signature and place the date as well on the appropriate places. There is provision for the two witnesses to sign as well as for them to place the date on which they have signed as witness. It shall be noted that the date on which the Will was signed as well as the dates on which the witnesses have signed shall be the same. </p>
                               <p>The on-line Will making product facility will, once subscribed to, be available for a period of 30 calendar days after which all the data will be irretrievably purged automatically by the systems of W&M and if you need to create the Will again, you will need to purchase a new package to get the data base facility and then input the details all over again. </p></li>
                           <li><b>Will Location Register:</b>
                           <p>The price of this package in indicated on the pricing as well as below the  Package details </p>
                       </ol>
                   </li>

                   <li>Payment for facilities and services provided by us is made in the following manner and on the following terms:
                       <ol type="a">
                           <li>Upon clicking on the “BUY” button in the pricing package of your choice, you will be directed to a payment page and you will receive a payment instruction bearing his name and address, the total amount payable including the applicable GST along with options for online payment through Paypal, Razorpay and PayTM or any other options that may be added as we progress. </li>

                           <li>Payment is affected through the separate facility/webpage provided by the respective payment gateway provider and is not under our control; we will not be responsible for any loss or damage due to any malfunction of the facility/webpage provided by the respective payment gateway provider. </li>

                           <li>In case your attempt at payment fails for any reason, the respective payment gateway provider will inform you on the mobile number or email address provided by you to them and further steps including refund of amounts debited to your account or retrying of payment will be intimated and carried out by the respective payment gateway provider.</li>
                       </ol>
                   </li>

                   <li>Upon successful completion of payment and on receipt by us of confirmation of payment from the respective payment gateway provider: -
                       <ol type="a">
                           <li>We will send to the email address provided by you, a Registration Certificate containing a unique Client ID, which can be used to search for proceeding with the facilities so availed by you including “Registration of the location” of your Will and/or Letter of Instructions stored with us or the Will drafting data base section etc. </li>
                           <li>A receipt for the payment received and an invoice containing the particulars of Goods and Services Tax (“GST”) raised by us on you.</li>
                       </ol>
                   </li>

                   <li>If you have chosen the “BASIC” package,
                       <ol type="a">
                           <li>you will be directed to the “Download Will Template” page. You will be offered a choice of Will and Codicil templates; you can choose all or any of them by ticking the box next to each Will Template. </li>
                           <li>In order to know more about each Will or Codicil template, you can click on the words “know more” in the box relating to each Will or Codicil template. </li>
                           <li>Upon clicking on the “Download” button, the relevant file in Microsoft Word format will be downloaded to your computer. A copy of the Will/Codicil templates chosen by you will also be sent to the email address provided by you at the time of registration. </li>
                           <li>You will not be required to create a username or password in order to download a Will template. </li>
                           <li>The Will/Codicil Templates made available for download by us are in Microsoft Word format; you will have to separately purchase and/or download the necessary software to access the contents of the Will/Codicil Templates. We will not be liable or responsible for any loss or damage arising from the use of such software. </li>
                           <li>The Will/Codicil Templates made available for download by us are intended to help you write your Will or Codicil and the contents are suitable for use by an ordinary and prudent person with sufficient knowledge of the English Language and operation of computers and relevant software. We have made available one Will Template for download in the Hindi Language, Devanagari script. </li>
                           <li>However, the Will templates made available by us may not cover all individual circumstances and special circumstances. </li>
                           <li>In case you need further advice regarding preparation of your Will or Codicil using the Will/Codicil Template made available for download by us, you may be required to seek the assistance of a qualified and duly registered Advocate. </li>
                           <li>Any Will or Codicil created by you using the Will/Codicil Templates made available by us is at your risk. </li>
                       </ol>
                   </li>

                   <li>If you have chosen the “Standard” package, you will be directed to a “Register” page. On the said page, you will be required to create a username and password as well as provide certain details. Upon filling in all mandatory details and clicking on the button “Save & Next”, you will be directed to the Member Home tab on the left-hand side menu on the Member Services page. You can choose any of the following services indicated in the tabs on the left-hand side menu.
                       <ol type="A">
                           <li><b>“Details of Nominees”</b>
                               <ol type="a">
                                   <li>You may register with us the names and other details of not more than 3 persons to whom we are duly authorised and permitted by you (“Nominees”) to communicate the location of your Will as registered by you with us and the Letter of Instructions as recorded/stored by you with us in the event of us receiving notice/information regarding your death or permanent disability (only in case of Letter of Instructions). </li>
                                   <li>You can make changes to the names and details of Nominees free of charge within 30 days of registration and thereafter, upon payment of a fee of Rs.250/- plus applicable GST, provided your membership/account is valid and subsisting. </li>
                                   <li>By registering the names and other details of the Nominees,
                                   <ol type="i">
                                       <li>You agree you accept, understand, and authorise us to transmit the said information/ documents to the Nominees; you further accept and understand, that we will be absolved of all liability and responsibility in connection with and in relation to such transmission; </li>
                                       <li>you agree and declare that the transmission of such information/ documents to the Nominees shall not constitute any breach of your confidentiality and privacy; </li>
                                       <li>you agree and accept that the location of your Will as registered with us (and as amended from time to time) shall be communicated to the Nominees only be consequent to your demise; </li>
                                       <li>you agree and accept that the Letter of Instructions recorded/stored with us (and as amended from time to time) shall be communicated to the Nominees only consequent to your demise or upon you being medically declared to be suffering from certain debilitating illness like Alzheimer’s disease and or total permanent disability and upon  a request being received by us in writing along with valid copies of the death certificate or medical certificates. </li>
                                   </ol>
                               </ol>
                           </li>

                           <li><b>“Will Location Details”</b>
                               <ol type="a">
                                   <li>You can register the location of your Last Will with us by providing details in the web page that opens when you click on the tab “Will Location Details”. </li>
                                   <li>You can make changes to the Location of your Will free of charge at your convenience through the W&M website using your secure password.
                                   <b>NOTE:</b> It may be noted that if you change the storage location of your Will (physical copy) but fail to register/note the new location in the Will location register offered to you, the facility will be rendered useless as your Executors/Beneficiaries/nominees will not be able to easily retrieve it from the last registered location as the documents location has since been moved by you. </li>
                                   <li>You agree that the information provided by you is accurate, correct and complete in all respects; W&M shall not be liable or responsible for any inconvenience, loss or damage that arises from inaccurate, incorrect and incomplete information provided by you in relation to the physical location of your Will. You further agree that you have noted/provided the information of your Will document location on your own free will and not based on any threat or coercion or undue influence. </li>
                                   <li>You agree that you accept, understand, and authorise W&M to, after your demise, transmit the said location details/information to your Executor/Nominees/Beneficiaries by email or other modes of communication; you further accept and understand, that we will be absolved of all liability and responsibility in connection with and in relation to such transmission and declare that the transmission of such information/ documents to the Executor/Nominees/Beneficiaries shall not constitute any breach of the confidentiality of the said information and/or your privacy; </li>
                                   <li>You agree and accept that the location of your Will as registered with us (and as amended/changed from time to time) shall be transmitted to the Executors/Nominees/beneficiaries only upon us being informed of your demise and after the same is duly verified by us from Death Certificates duly issued and/or other documents and records submitted to us and we being satisfied of their veracity. </li>
                               </ol>
                           </li>

                           <li><b>Storing a scanned copy of your Will</b>
                               <p>We provide Clients/Members a facility to store a scanned copy of their last executed Will which can be passed on to the Executors/Beneficiaries/ Nominees after the demise of the Client/Member. The facility includes withdrawal of a scanned copy and replacing it (at the option of the Client/Member) with the latest scanned copy of the Will document. As stated by us in other sections, a scanned copy of the Will has no legal evidentiary value and will not be entertained by a court of law or any Official as being the same as an original Will. It can at best serve as a guide to the legal heirs/ Executors/ Administrators or perhaps even a court in progressing or deciding on matters related to the manner of distribution of the assets of a deceased person. </p>
                           </li>

                           <li><b>“Letter of Instructions”</b>
                               <ol type="a">
                                   <li> You can record or store within our facilities a Letter of Instructions to your loved ones by providing details in the relevant web page that opens when you click on the tab “Letter of Instructions” and purchase the facility. The Letter of Instructions can either be uploaded and stored by you in a .doc, .jpeg or .pdf formats or can be recorded in a text form in the space provided to you. </li>
                                   <li> You can make changes to the Letter of Instructions free of charge during the period of the offer of the facility/membership. </li>
                                   <li> You accept, agree and understand that a Letter of Instructions is not a Will or a substitute for a Will and that a Letter of Instructions is a personal document written to the family giving them important information they need to know and may also include your desire on the manner of accessing your assets or valuables consequent to your permanent incapacitation or you being afflicted with adverse sickness including Alzheimer or stroke or Parkinson’s disease etc rendering you incapable of acting on your own so as to facilitate your loved ones to access funds to cater to your needs etc. It also facilitates manner of handling and/or entrusting certain assets that you do not want to add into your Will like for instance certain antique furniture or preferred crockery or stamp/coin collections, trophies etc. You may also want your loved ones to conduct certain religious / family rituals in a particular manner. All these can be added into the Letter of instructions. </li>
                                   <li> You agree that the information provided by you in the Letter of Instructions is accurate, correct and complete in all respects; we shall not be liable or responsible for any inconvenience/loss or damage that arises from inaccurate, incorrect and incomplete information provided by you. You further agree that you have provided the information on your own free will and not based on any threat, undue influence or coercion. </li>
                                   <li> You agree you accept, understand, and authorise us to transmit the Letter of Instructions to the Nominees by email; you further accept and understand, that we will be absolved of all liability and responsibility in connection with and in relation to such transmission and declare that the transmission of such information/ documents to the Nominees shall not constitute any breach of the confidentiality of the said information and/or your privacy and confidentiality; </li>
                                   <li> You agree and accept that the Letter of Instructions as lodged/stored with us (and as amended by you from time to time) shall be ordinarily transmitted to the Nominees upon us being informed of your incapacitation or infliction with critical ailment / demise and after the same is duly verified by us from Medical/Death Certificates duly issued and/or other documents and records. However, you also agree that the Letter of Instructions alone can be made available to the Nominees on a specific declaration and request by your legal heirs or the Nominees in the event of your permanent or total incapacitation due to accidents, or debilitating illnesses like Alzheimer’s or Parkinson’s disease, or any other condition (that would render a person of unsound mind), upon submission of valid medical documents/certificates and due verification.</li>
                               </ol>
                           </li>

                           <li><b>Customised Will</b>

                               <p>This is yet another facility that Will & More offers to its clients. </p>
                               <p>It may so happen that you may have specific or specialised requirements to draw out your Will owing to certain complexities in relationships or specifications to be catered to your loved ones like aged parents or spouse or children with special needs or the location of certain assets or property in a foreign country or the need to bequeath assets to orphanages or certain institutions that meet certain criterion etc., that an on-line structured Will document may not be capable of capturing. </p>
                               Hence, at W&M we are bring to you a specialised service through which your particular needs will be met and a specific type of Will document drafted especially for you. </p>
                               <p>In order to avail of this facility, you shall have to get in touch with us at the email Id or the telephone that is assigned for this purpose and our expert legal adviser will attend to your requirements in confidence. The price for this facility/service will vary based on the requirement and complexities of each matter. </p>
                               <p>In the past many persons have sought our services for a customised Will and have received our expert advice and have finalised their Wills. </p>

                               <ol type="A">
                                   <li><b>“Details of Nominees” to register names of nominees,</b>
                                       <ol type="a">
                                           <li>You may register with us the names and other details of not more than 3 persons to whom we are duly authorised and permitted by you (“Nominees”) to communicate the location of your Will as registered by you with us and the Letter of Instructions as recorded/stored by you with us in the event of us receiving notice/information regarding your death or permanent disability (only in case of Letter of Instructions). </li>
                                           <li>You can make changes to the names and details of Nominees free of charges provided your membership/account is valid and subsisting. </li>
                                           <li>By registering the names and other details of the Nominees,
                                               <ol type="i">
                                                   <li>you accept, understand, and authorise Bequest/us to part with the said information/ documents to the Nominees; </li>
                                                   <li>you further accept and understand, that we will be absolved of all liability and responsibility in connection with and in relation to such transmission; </li>
                                                   <li>you agree and declare that the transmission of such information/ documents to the Nominees shall not constitute any breach of Your confidentiality and privacy; </li>
                                                   <li>you agree and accept that the location of your Will as registered with us (and as amended from time to time) shall be communicated to the Nominees only be consequent to your demise; </li>
                                                   <li>you agree and accept that the Letter of Instructions recorded/stored with us (and as amended from time to time) shall be communicated to the Nominees only be consequent to your demise or upon you being medically declared to be suffering from certain debilitating illness like Alzheimer’s disease and or total permanent disability and upon a request being received by us in writing along with valid copies of the death certificate or relevant medical certificates.</li>
                                               </ol>
                                           </li>
                                       </ol>
                                   </li>
                               </ol>
                           </li>
                       </ol>
                   </li>

                   <li>If you forget the username or password, you can retrieve the same using the forgot username or forgot password links on the login page. Upon successful log in, you will be directed to the Member Home tab on the Member Services Page. You can avail of the facilities and services offered by us by choosing the appropriate available facility or service from the left-hand side menu. </li>

                   <li>We reserve the right to terminate accounts created by users who appropriate the name, e-mail address, or other personally identifiable information of another individual or provide incomplete or improper personal details like e-mail address, name, number or other personal identifiable information. </li>

                   <li>We also reserve the right to refuse to approve a user account or terminate an existing user account with or without cause or notice (other than any notice required by applicable law and not waived herein) for any reason at any time. </li>

                   <li>We are not liable for any losses or damages incurred by you as a result of the termination of your account or refusal of the service. </li>

                   <li>The login credentials; i.e.; username and password which are created successfully are for the personal use of a customer and are non-transferable and non-assignable. The customer shall be solely liable in case of any misuse of the said login credentials. The customer is required to forthwith intimate us in case of any misuse of the login credential or any unauthorized access to their account; in such a case we shall take the necessary steps to remedy the same. </li>

                   <li>As a customer, you are solely responsible for maintaining the confidentiality of your login credential and password. You shall not share your account with anyone else and agree not to share your account, username or password with anyone else. You shall also not disclose your password to anyone else and agree to have only one account. You agree to exit from your account at the end of each session and to take all reasonable precautions to prevent others from using your account. You further agree to notify us immediately of any unauthorized use of your account</li>

                   <li>You are advised to exercise full caution while entering any transaction or information through the website as you would be completely, solely & invariably responsible for all resultant implications & consequence, financial or otherwise. </li>


                   <h4>SEARCH Facility: </h4>

                   <li>We provide a facility to search for Will Location details and/or Letter of Instructions of a deceased person; any person who has a copy of the deceased persons details and Death Certificate can search for his/her Will location and/or Letter of Instructions using our website. </li>

                   <li>A similar Search facility is also made available in the case of a person suffering from certain permanent debilitating illness. </li>

                   <li>The search is done through the following process:
                       <ol type="a">
                           <li>You can initiate the search by clicking on the tab “WILL LOCATION SEARCH” in the menu bar; upon doing so, you will be directed to “Search the Will” page; </li>
                           <li>On the “Search the Will” page, you will need to enter your personal details including details of documents to establish your identity – these include Aadhar Number or Passport. You will also need to upload a copy of the identity document and then click on the button “SAVE & NEXT”; </li>
                           <li>On the following page, you will need to enter the details of the deceased person and upload of copy of the Death Certificate and /or the relevant medical certificate regarding that persons debilitating illness and an identity proof of the deceased person. </li>
                           <li>On the following page, you will need to provide a reason for the search; </li>
                           <li>Based on the details provided by you, an automated and electronic search of our records is conducted and if it is found that the deceased person had registered as a Member with us, you will be directed to a payment page. </li>
                           <li>On the payment page, you will receive a payment instruction bearing the total amount payable including the applicable GST along with options for online payment through PayPal, Razor pay and Paytm. A fee of Rs.2,500/- plus applicable GST is payable for conducting the search. </li>
                           <li>Payment is affected through the separate facility/webpage provided by the respective payment gateway provider and is not under our control; we will not be responsible for any loss or damage due to any malfunction of the facility/webpage provided by the respective payment gateway provider. </li>
                           <li>In case your attempt at payment fails for any reason, the respective payment gateway provider may inform you on the mobile number or email address provided by you to them and further steps including refund of amounts debited to your account or retrying of payment will be intimated and carried out by the respective payment gateway provider. </li>
                           <li>Upon successful completion of payment and on receipt by us of confirmation of payment from the respective payment gateway provider:
                               <ol type="i">
                                   <li>We will validate the details of the deceased and of the Death Certificate provided and upon validation, we will send the Will location and Letter of Instruction by email to the Nominees whose name has been registered with us.</li>
                                   <li>We will also send by email to you a receipt for the payment received and an invoice containing the particulars of Goods and Services Tax (“GST”) raised by us on you.</li>
                               </ol>
                           </li>
                           <li>Since membership terminates upon death, after validating the death of the member and after transmitting the Will Location and/or Letter of Instructions to Nominees, unless otherwise required of us under applicable laws or by a competent authority including a court of law, all data relating to the same will be purged from our records</li>
                       </ol>
                   </li>

                   <li>You agree accept, understand, and authorise us to transmit the Will Location details and Letter of Instructions to the Nominees by email in the event that the search reveals that the deceased was registered with us as a member; you further accept and understand, that we will be absolved of all liability and responsibility in connection with and in relation to such transmission and declare that the transmission of such information/ documents to the Nominees shall not constitute any breach of the confidentiality of the said information and/or your privacy. </li>

                   <li>With regard to your membership by virtue of which you avail various facilities and services offered by us, you agree that: -
                       <ol type="a">
                           <li>Membership is for a block of a 5-year period commencing from the date of the grant of admission up to the corresponding date in the 5th year. </li>

                           <li>Membership fees (along with the appliable GST) are payable in advance for the entire block of 5 years. </li>

                           <li>Membership Fees i.e. the cost of purchase of packages, once remitted/ paid are not refundable under any circumstance. </li>
                           <li>Members are entitled to seek the renewal and therefore continuance of membership after the five-year period but within 30 days of the expiry of the Membership. </li>

                           <li>The offer of continuation of Membership will be subject to the payment of the Membership fees as prevailing as on the date of the renewal. </li>

                           <li>The grant of renewal of facility/Membership is however, subject to the satisfaction and the discretion of Bequest. </li>

                           <li>Any decision not to grant the renewal of membership to a Member shall result in the withdrawal of all the membership facilities and unless otherwise required of us under applicable laws or by a competent authority including a court of law, each and every document and information that is registered, stored or recorded by the Member during his earlier membership period will be purged from our records.</li>
                       </ol>
                   </li>

                   <li><b>Cancellation and Refund</b>
                       <ol type="1">
                           <li>A Member or Client may make seek cancellation of his Membership and request for the refund of the fees remitted in case of membership to the Basic Package if such requests are made to and received by W&M within a period of 24 hours of remittance and /or before the Will data base templates are transmitted by W&M to the Member over email or the Member downloads the Will Templates from the links sent to him by W&M. The client can write to assistance@willandmore.com stating the specific request. </li>

                           <li>Any refund of fees if determined by W&M will be processed within 3 to 5 working days and refund effected. </li>

                           <li>It shall be the sole discretion of W&M to determine whether a particular case is appropriate for full refund or not. </li>

                           <li>Any refunds made shall be subject to deduction of payment gateway charges by paid by W&M where applicable. </li>

                           <li>There will be no refund of the GST component so charged once the invoice is issued.</li>
                       </ol>
                   </li>

                   <li>The Directors of Bequest Records Pvt Ltd wish all Users and Members a happy relationship with the Company, a beneficial use of its web site and the facilities offered to Members so that the members of your family and your loved ones gain a peaceful and enjoyable continuity of their regard for you. </li>

                   <p class="btm-text-trem"><b><i>We wish that your loved ones only remember and feel your presence around them and never feel your absence!</i></b></p>
               </ol>
          </div>


          <div class="prvt-txt-bg">

          </div>
       </div>
    </div>
 </div>

@endsection
@section('footer')
@include('includes.footer')
@endsection
@section('script')
@include('includes.scripts')
@endsection
